dist: bionic
sudo: true
language: java
jdk: openjdk11

services:
  - xvfb

matrix:
  include:
    - dist: bionic
      jdk: openjdk11
      sudo: false
      env: JENV=openjdk11

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - chmod +x ./gradlew
  - export DISPLAY=:99.0

install: true

script:
  - ./gradlew
